import csv, datetime as dt, os, time
from pathlib import Path
from dotenv import load_dotenv
import mediacloud.api

BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")
search = mediacloud.api.SearchApi(os.environ["MEDIACLOUD_API_KEY"])
COLLECTION_ID = 9272347


def with_retry(fn, max_attempts=6):
    delay = 4.0
    for attempt in range(max_attempts):
        try:
            return fn()
        except Exception as e:
            if "429" in str(e) and attempt < max_attempts - 1:
                time.sleep(delay)
                delay = min(delay * 1.8, 25)
                continue
            raise
    return None


# Extra transliteration variants per location, generated by hand from the
# documented Arabic->English variance patterns (ya/i/ee, waw/u/w, ta-marbuta
# -a/-e, al- prefix in/out, double consonants, qaf as q/k, kha/ha, tha/dh),
# beyond what's already in location_aliases.csv, to test whether the
# original alias set was inadequate.
EXTRA_VARIANTS = {
    "LD-2026-03-23-عيتيت (Aitit)": ["Aitite", "Aytite"],
    "LD-2026-03-15-عيتيت (Aitit)": ["Aitite", "Aytite"],
    "LD-2026-03-07-جبشيت (Jbeshit)": ["Jbisheet", "Jbeshiyt"],
    "LD-2026-03-31-جبشيت (Jbeshit)": ["Jbisheet", "Jbeshiyt"],
    "LD-2026-03-07-كفرتبنيت (Kfartebnit)": ["Kfar Tibnit", "Kafr Tebnit"],
    "LD-2026-03-27-البزالية (Bzaaliyeh)": ["Al-Bzaaliyeh", "Bzalliyeh"],
    "LD-2026-03-07-ميفدون (Meifadoun)": ["Maifadoun", "Meifdoune"],
    "LD-2026-03-14-ميفدون (Meifadoun)": ["Maifadoun", "Meifdoune"],
    "LD-2026-03-31-Ain al-Mazraab road (Tibnine)": ["Ain el-Mazraab", "Ein al-Mazraab"],
    "LD-2026-03-03-صديقين (Saddiqine/Siddiqine)": ["Sadiqin", "Saddikine"],
    "LD-2026-03-11-برج الشمالي (Burj al-Shamali)": ["Burj Chemali", "Bourj Shamali"],
    "LD-2026-03-13-طريق الشعيتية (Al-Shaitiyeh road)": ["Chaitiyeh", "Al-Chaitiyeh"],
    "LD-2026-03-29-شقرا (Shaqra)": ["Shakraa", "Chakra"],
    "LD-2026-03-10-الحوش (Al-Hosh)": ["El Hosh", "Al-Hawsh"],
    "LD-2026-03-06-صيدا (Sidon)": ["Makassed hospital", "Al-Makassed"],
    "LD-2026-03-20-بافيله (Bafiliyeh)": ["Bafilye", "Al-Bafiliyeh"],
    "LD-2026-03-21-زوطر الشرقية (Zawtar al-Sharqiya)": ["Zawtar Sharqiya", "Zoutar Charqiyeh"],
    "LD-2026-03-27-زوطر الشرقية (Zawtar al-Sharqiya)": ["Zawtar Sharqiya", "Zoutar Charqiyeh"],
    "LD-2026-03-05-القليلة (Qlaile)": ["Qulayleh", "Al-Qlaile"],
    "LD-2026-03-06-السعيدة (Saaideh)": ["Al-Saaida", "Saeedeh"],
    "LD-2026-03-29-عبا (Aaba)": ["Abba", "Al-Aaba"],
    "LD-2026-03-31-عبا (Aaba)": ["Abba", "Al-Aaba"],
    "LD-2026-03-10-قلاويه (Qalawiyeh)": ["Kalawiyeh", "Al-Qalawiyeh"],
    "LD-2026-03-22-الصوانة (Al-Sawwaneh)": ["Sawaneh village", "As-Sawwaneh"],
    "LD-2026-03-15-مجدل سلم (Majdal Selem)": ["Majdel Silim", "Majd al-Silm"],
}

with open(BASE_DIR / "data" / "processed" / "coverage_results_FINAL.csv", encoding="utf-8-sig") as f:
    rows = {r["location_day_id"]: r for r in csv.DictReader(f)}
with open(BASE_DIR / "scripts" / "uncovered_audit_sample_ids.txt", encoding="utf-8") as f:
    sample_ids = [l.strip() for l in f if l.strip()]

with (BASE_DIR / "scripts" / "25_uncovered_audit.progress.log").open("w", encoding="utf-8") as log:
    for ldid in sample_ids:
        r = rows.get(ldid)
        if not r:
            log.write(f"{ldid.encode('ascii','backslashreplace').decode('ascii')}: NOT FOUND\n")
            continue
        event_date = dt.date.fromisoformat(r["event_date"])
        end7 = event_date + dt.timedelta(days=7)

        extras = EXTRA_VARIANTS.get(ldid, [])
        base_query = r["query_used"].split(" | fallback:")[0].replace("base:", "").strip()
        # build an alt query: original alias clause OR'd with the new extra variants
        if extras:
            extra_clause = " OR ".join(f'"{e}"' for e in extras)
            # splice extras into the alias parenthetical if present, else just AND them in
            if base_query.startswith("("):
                close_idx = base_query.index(")")
                alt_query = base_query[:close_idx] + f' OR {extra_clause}' + base_query[close_idx:]
            else:
                alt_query = f'({extra_clause}) AND Lebanon'
        else:
            alt_query = base_query

        try:
            page, _ = with_retry(lambda: search.story_list(alt_query, start_date=event_date, end_date=end7, collection_ids=[COLLECTION_ID], page_size=10))
        except Exception as e:
            log.write(f"{ldid.encode('ascii','backslashreplace').decode('ascii')}: ERROR {e}\n\n")
            continue

        log.write(f"{ldid.encode('ascii','backslashreplace').decode('ascii')} | extras={extras} | n_d7={len(page)}\n")
        log.write(f"  query: {alt_query}\n")
        for s in page[:5]:
            log.write(f"    [{s.get('media_name','')}] {s.get('title','').encode('ascii','backslashreplace').decode('ascii')} | {s.get('publish_date','')}\n")
        log.write("\n")
        time.sleep(1.2)

    log.write("=== done ===\n")
